# -*- coding: utf-8 -*-
"""PSR T-TEST in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JQI3_b8E-VmkQnEiaoyRbPbzYKYB5svF
"""

#code to calculate Standard Deviation,t-statistics,degrees of freedom
# Import the packages
import numpy as np
from scipy import stats

## Define 2 groups with their respective data
#Sample Size
N = 10.0
#Data of group 1 of rtx20 series
a = np.array([89.0,83.0,81.0,85.0,84.0])
#Data of group 2 of rtx 30 series
b = np.array([115.0,89.0,86.0,92.0,94.0])

## Calculate the Standard Deviation
#Calculate the variance to get the standard deviation

var_a = a.var(ddof=1.0)
var_b = b.var(ddof=1.0)

#std deviation
s = np.sqrt((var_a + var_b)/2.0)
print("Standard Deviation is: %s" %s)

## Calculate the t-statistics
t = (a.mean() - b.mean())/(s*np.sqrt(2.0/N))

## Compare with the critical t-value
#Degrees of freedom
df = len(a) + len(b) - 2.0
print("Degrees of Freedom: %s" %df)

#p-value after comparison with the t
p = stats.t.cdf(t,df=df)

print("t-value = " + str(t))
print("p-value = " + str(2.0*p))